// function selected(element) {
//     element.classList.toggle("pressed"); 
// }


// const btnChoice1 = document.getElementById("btn-choice1"); 

// btnChoice1.addEventListener("click", () => {
//     console.log('hello');
//     btnChoice1.insertAdjacentHTML("afterend", `<p>Hej</p>`);
// });

// const btnChoice2 = document.getElementById("btn-choice2"); 

// btnChoice2.addEventListener("click", () => {
//     console.log('hello2');
//     btnChoice2.style.background="#2A6026";
//     btnChoice2.style.color="#FFFFFF";
// });

// const btnChoice3 = document.getElementById("btn-choice3"); 

// btnChoice3.addEventListener("click", () => {
//     console.log('hello3');
//     btnChoice3.style.background="#2A6026";
//     btnChoice3.style.color="#FFFFFF";
// });


// --------------- CITIES -------------------

document.ready(function() {
    const cities = [
        "Örebro",
        "Kungsbacka",
        "Örnsköldsvik",
        "Kungälv",
        "Bollebygd",
        "Falkenberg",
        "Uppsala",
        "Ale",
        "Nyköping",
        "Linköping",
        "Klippan",
        "Knivsta",
        "Övertorneå",
        "Norrtälje",
        "Borgholm",
        "Norrköping",
        "Österåker",
        "Grums",
        "Ludvika",
        "Orsa",
        "Ängelholm",
        "Bromölla",
        "Sala",
        "Finspång",
        "Piteå",
        "Östhammar",
        "Söderhamn",
        "Falun",
        "Mönsterås",
        "Håbo",
        "Eksjö",
        "Lidköping",
        "Mark",
        "Ulricehamn",
        "Gagnef",
        "Karlstad",
        "Orust",
        "Forshaga",
        "Sotenäs",
        "Lycksele",
        "Ovanåker",
        "Mellerud",
        "Karlskrona",
        "Mora",
        "Trosa",
        "Mjölby",
        "Ekerö",
        "Vännäs",
        "Dorotea",
        "Gnosjö",
        "Lerum",
        "Umeå",
        "Hudiksvall",
        "Ockelbo",
        "Ronneby",
        "Oskarshamn",
        "Höganäs",
        "Växjö",
        "Ystad",
        "Värnamo",
        "Sundsvall",
        "Lindesberg",
        "Alvesta",
        "Hagfors",
        "Nässjö",
        "Munkfors",
        "Boden",
        "Söderköping",
        "Gotland",
        "Borlänge",
        "Gullspång",
        "Motala",
        "Mörbylånga",
        "Skellefteå",
        "Kumla",
        "Göteborg",
        "Gällivare",
        "Lysekil",
        "Höör",
        "Smedjebacken",
        "Krokom",
        "Lilla Edet",
        "Gävle",
        "Degerfors",
        "Borås",
        "Lessebo",
        "Västerås",
        "Landskrona",
        "Hässleholm",
        "Vansbro",
        "Nordanstig",
        "Jokkmokk",
        "Tranås",
        "Hällefors",
        "Sunne",
        "Bräcke",
        "Åre",
        "Tingsryd",
        "Rättvik",
        "Simrishamn",
        "Tierp",
        "Sölvesborg",
        "Alingsås",
        "Järfälla",
        "Karlskoga",
        "Svedala",
        "Vetlanda",
        "Östra Göinge",
        "Uddevalla",
        "Jönköping",
        "Avesta",
        "Filipstad",
        "Berg",
        "Härryda",
        "Båstad",
        "Tomelilla",
        "Katrineholm",
        "Askersund",
        "Karlsborg",
        "Ljusdal",
        "Eskilstuna",
        "Trelleborg",
        "Gislaved",
        "Kristianstad",
        "Sollefteå",
        "Töreboda",
        "Hofors",
        "Hultsfred",
        "Leksand",
        "Lekeberg",
        "Vellinge",
        "Vallentuna",
        "Härjedalen",
        "Malung",
        "Torsby",
        "Hylte",
        "Sandviken",
        "Helsingborg",
        "Södertälje",
        "Essunga",
        "Olofström",
        "Varberg",
        "Säter",
        "Åstorp",
        "Luleå",
        "Arvika",
        "Kävlinge",
        "Värmdö",
        "Aneby",
        "Kalmar",
        "Karlshamn",
        "Ödeshög",
        "Laholm",
        "Bollnäs",
        "Svalöv",
        "Pajala",
        "Älvdalen",
        "Huddinge",
        "Skurup",
        "Arvidsjaur",
        "Strömstad",
        "Eslöv",
        "Ånge",
        "Åsele",
        "Mariestad",
        "Tidaholm",
        "Sävsjö",
        "Götene",
        "Boxholm",
        "Stenungsund",
        "Tranemo",
        "Halmstad",
        "Sjöbo",
        "Bjuv",
        "Ljusnarsberg",
        "Vindeln",
        "Nybro",
        "Kramfors",
        "Trollhättan",
        "Hörby",
        "Ljungby",
        "Kiruna",
        "Härnösand",
        "Upplands-Bro",
        "Burlöv",
        "Malmö",
        "Nynäshamn",
        "Strängnäs",
        "Storfors",
        "Markaryd",
        "Dals-Ed",
        "Färgelanda",
        "Nora",
        "Tjörn",
        "Storuman",
        "Haninge",
        "Robertsfors",
        "Östersund",
        "Hallstahammar",
        "Nykvarn",
        "Lund",
        "Västervik",
        "Hallsberg",
        "Kalix",
        "Salem",
        "Kil",
        "Uppvidinge",
        "Mölndal",
        "Tibro",
        "Nacka",
        "Älvkarleby",
        "Nordmaling",
        "Vara",
        "Surahammar",
        "Kristinehamn",
        "Staffanstorp",
        "Timrå",
        "Bengtsfors",
        "Älmhult",
        "Vingåker",
        "Habo",
        "Vimmerby",
        "Munkedal",
        "Enköping",
        "Hedemora",
        "Lidingö",
        "Tanum",
        "Heby",
        "Skövde",
        "Köping",
        "Hammarö",
        "Örkelljunga",
        "Eda",
        "Botkyrka",
        "Danderyd",
        "Torsås",
        "Skara",
        "Vadstena",
        "Vaggeryd",
        "Perstorp",
        "Vårgårda",
        "Falköping",
        "Åtvidaberg",
        "Älvsbyn",
        "Kinda",
        "Svenljunga",
        "Överkalix",
        "Haparanda",
        "Partille",
        "Osby",
        "Sigtuna",
        "Fagersta",
        "Valdemarsvik",
        "Stockholm",
        "Herrljunga",
        "Sollentuna",
        "Säffle",
        "Gnesta",
        "Ydre",
        "Vilhelmina",
        "Lomma",
        "Flen",
        "Sorsele",
        "Täby",
        "Hjo",
        "Tyresö",
        "Strömsund",
        "Mullsjö",
        "Emmaboda",
        "Kungsör",
        "Upplands Väsby",
        "Högsby",
        "Vänersborg",
        "Skinnskatteberg",
        "Laxå",
        "Öckerö",
        "Norberg",
        "Ragunda",
        "Solna",
        "Arboga",
        "Malå",
        "Årjäng",
        "Åmål",
        "Oxelösund",
        "Vaxholm",
        "Norsjö",
        "Bjurholm",
        "Grästorp",
        "Sundbyberg",
        "Arjeplog"
    ];

    document.getElementById("cities").autocomplete({
        source: cities
    });
});